version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - nilerr
    - copyloopvar

formatters:
  enable:
    - gofmt
